# Generated by Django 6.0 on 2025-12-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_article_name_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='Автор', max_length=20, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
